using CarRental.Api.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace CarRental.Api.Data;

public static class DatabaseInitializer
{
    private const string AdminEmail = "admin@rentauto.local";
    private const string AdminPassword = "Admin123!";

    public static async Task InitializeDatabaseAsync(this WebApplication app)
    {
        await using var scope = app.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        await db.Database.EnsureCreatedAsync();
        await EnsureLegacySchemaAsync(db);
        await EnsureAdminExistsAsync(db);
        await LinkLegacyRentalsToUsersAsync(db);
    }

    private static async Task EnsureLegacySchemaAsync(AppDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Users" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" text NOT NULL,
                "Email" text NOT NULL,
                "PasswordHash" text NOT NULL,
                "Role" text NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
            """);

        await db.Database.ExecuteSqlRawAsync(
            "ALTER TABLE \"Rentals\" ADD COLUMN IF NOT EXISTS \"UserId\" integer NULL;");
    }

    private static async Task EnsureAdminExistsAsync(AppDbContext db)
    {
        if (await db.Users.AnyAsync(user => user.Email == AdminEmail)) return;

        var admin = new AppUser
        {
            Name = "Администратор",
            Email = AdminEmail,
            Role = "Admin"
        };
        admin.PasswordHash = new PasswordHasher<AppUser>().HashPassword(admin, AdminPassword);

        db.Users.Add(admin);
        await db.SaveChangesAsync();
    }

    private static async Task LinkLegacyRentalsToUsersAsync(AppDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Rentals" AS rental
            SET "UserId" = app_user."Id"
            FROM "Users" AS app_user
            WHERE rental."UserId" IS NULL
              AND lower(rental."CustomerName") = lower(app_user."Name");
            """);
    }
}
