using CarRental.Api.Data;
using CarRental.Api.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddDbContext<AppDbContext>(o => o.UseNpgsql(builder.Configuration.GetConnectionString("Default")));
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o => o.TokenValidationParameters = new()
{
    ValidateIssuerSigningKey = true, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Key"]!)),
    ValidateIssuer = false, ValidateAudience = false, ValidateLifetime = true
});
builder.Services.AddAuthorization();
var app = builder.Build();
app.UseSwagger(); app.UseSwaggerUI(); app.UseCors(); app.UseAuthentication(); app.UseAuthorization(); app.MapControllers();
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>(); await db.Database.EnsureCreatedAsync();
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "Users" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "Email" text NOT NULL,
            "PasswordHash" text NOT NULL,
            "Role" text NOT NULL
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
        """);
    await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Rentals\" ADD COLUMN IF NOT EXISTS \"UserId\" integer NULL;");
    if (!await db.Users.AnyAsync(x => x.Email == "admin@rentauto.local"))
    {
        var admin = new AppUser { Name = "Администратор", Email = "admin@rentauto.local", Role = "Admin" };
        admin.PasswordHash = new PasswordHasher<AppUser>().HashPassword(admin, "Admin123!");
        db.Users.Add(admin); await db.SaveChangesAsync();
    }
    await db.Database.ExecuteSqlRawAsync("""
        UPDATE "Rentals" r SET "UserId" = u."Id"
        FROM "Users" u
        WHERE r."UserId" IS NULL AND lower(r."CustomerName") = lower(u."Name");
        """);
}
app.Run();
